services:
  client:
    container_name: client
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.target
    mac_address: ${MAC_CLIENT}
    networks:
      inquisitor:
        ipv4_address: ${IP_CLIENT}
  ftp-server:
    container_name: ftp-server
    privileged: true
    build:
      context: ./ftp-server
      dockerfile: Dockerfile.server
    ports:
      - 4243:21
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
    mac_address: ${MAC_SERVER}
    networks:
      inquisitor:
        ipv4_address: ${IP_SERVER}
  attacker:
    container_name: attacker
    mac_address: ${MAC_ATTACKER}
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.attacker
    environment:
      - IP_CLIENT=${IP_CLIENT}
      - IP_SERVER=${IP_SERVER}
      - MAC_CLIENT=${MAC_CLIENT}
      - MAC_SERVER=${MAC_SERVER}
    networks:
      inquisitor:
        ipv4_address: ${IP_ATTACKER}

networks:
  inquisitor:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
          gateway: 172.25.0.1