FROM debian:latest

RUN apt-get update -y && apt-get -y install vsftpd

COPY vsftpd.conf /etc/vsftpd.conf

EXPOSE 21 20

COPY entrypoint.sh .

RUN chmod +x entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]